# Generated by Django 3.1.4 on 2021-01-06 14:11

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='job_post_status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_post_status', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Search_with_price',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minimum_price', models.CharField(max_length=5000)),
                ('maximum_price', models.CharField(max_length=5000)),
            ],
        ),
        migrations.CreateModel(
            name='Product_Details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=500)),
                ('price', models.CharField(max_length=500)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='uploads/product_image')),
                ('image2', models.ImageField(upload_to='uploads/product_image')),
                ('status', models.CharField(max_length=500)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medicifyapp.categories')),
            ],
        ),
        migrations.CreateModel(
            name='posted_jobs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=1000)),
                ('job_details', models.TextField()),
                ('job_location', models.CharField(max_length=1000)),
                ('job_type', models.CharField(max_length=100)),
                ('salary', models.CharField(max_length=1000)),
                ('keywords', models.CharField(max_length=1000)),
                ('phone_number', models.CharField(max_length=1000)),
                ('post_date', models.DateField(blank=True, default=datetime.datetime(2021, 1, 6, 20, 11, 5, 490464))),
                ('email', models.CharField(max_length=1000)),
                ('job_post_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medicifyapp.job_post_status')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=1000)),
                ('items_json', models.TextField()),
                ('total_bill', models.CharField(max_length=1000)),
                ('full_address', models.TextField()),
                ('city', models.CharField(max_length=1000)),
                ('postal_code', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=1000)),
                ('phone', models.CharField(max_length=1000)),
                ('email', models.CharField(max_length=1000)),
                ('order_date', models.DateField(blank=True, default=datetime.datetime(2021, 1, 6, 20, 11, 5, 492464))),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
