# Generated by Django 3.1.4 on 2021-01-09 17:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicifyapp', '0007_auto_20210109_2316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 1, 9, 23, 20, 36, 836048)),
        ),
        migrations.AlterField(
            model_name='posted_jobs',
            name='post_date',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 1, 9, 23, 20, 36, 835049)),
        ),
        migrations.AlterField(
            model_name='product_details',
            name='price',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
