# Generated by Django 3.1.4 on 2021-01-09 17:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicifyapp', '0008_auto_20210109_2320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 1, 9, 23, 23, 32, 927333)),
        ),
        migrations.AlterField(
            model_name='posted_jobs',
            name='post_date',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 1, 9, 23, 23, 32, 926334)),
        ),
        migrations.AlterField(
            model_name='product_details',
            name='image',
            field=models.ImageField(blank=True, default='', null=True, upload_to='uploads/product_image'),
        ),
        migrations.AlterField(
            model_name='product_details',
            name='image2',
            field=models.ImageField(blank=True, default='', null=True, upload_to='uploads/product_image'),
        ),
        migrations.AlterField(
            model_name='product_details',
            name='image3',
            field=models.ImageField(blank=True, default='', null=True, upload_to='uploads/product_image'),
        ),
        migrations.AlterField(
            model_name='product_details',
            name='image4',
            field=models.ImageField(blank=True, default='', null=True, upload_to='uploads/product_image'),
        ),
        migrations.AlterField(
            model_name='product_details',
            name='image5',
            field=models.ImageField(blank=True, default='', null=True, upload_to='uploads/product_image'),
        ),
        migrations.AlterField(
            model_name='product_details',
            name='price',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
    ]
