# Generated by Django 3.1.4 on 2021-01-11 04:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicifyapp', '0009_auto_20210109_2323'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Search_with_price',
        ),
        migrations.AddField(
            model_name='posted_jobs',
            name='company_name',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='posted_jobs',
            name='qualification',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 1, 11, 10, 43, 41, 736359)),
        ),
        migrations.AlterField(
            model_name='posted_jobs',
            name='post_date',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 1, 11, 10, 43, 41, 736359)),
        ),
    ]
