# Generated by Django 3.1.4 on 2021-01-11 05:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicifyapp', '0010_auto_20210111_1043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 1, 11, 11, 50, 4, 465405)),
        ),
        migrations.AlterField(
            model_name='posted_jobs',
            name='company_name',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='posted_jobs',
            name='email',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='posted_jobs',
            name='job_details',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='posted_jobs',
            name='job_location',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='posted_jobs',
            name='job_title',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='posted_jobs',
            name='job_type',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='posted_jobs',
            name='keywords',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='posted_jobs',
            name='phone_number',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='posted_jobs',
            name='post_date',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 1, 11, 11, 50, 4, 464404)),
        ),
        migrations.AlterField(
            model_name='posted_jobs',
            name='qualification',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='posted_jobs',
            name='salary',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
