# Generated by Django 3.1.4 on 2021-01-12 12:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicifyapp', '0013_auto_20210111_1854'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posted_jobs',
            name='keywords',
        ),
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 1, 12, 18, 8, 21, 900200)),
        ),
        migrations.AlterField(
            model_name='posted_jobs',
            name='post_date',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 1, 12, 18, 8, 21, 899201)),
        ),
    ]
